version: "3.9"
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    environment:
      - MTX_CONFIG=/mediamtx.yml
